
name: inyection-data-script

on:
    # schedule: 
    #     - cron: "*/5 * * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: python config
              uses: actions/setup-python@v5
              with:
                python-version: '3.14'
            - name: install dependencies
              run: pip install pydantic requests pydantic-settings sqlalchemy
            - name: run script
              env:
                COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
                AUTOMATION_API_KEY: ${{ secrets.AUTOMATION_API_KEY }}
              run: python -m scripts.inyect
                
                